# Shadow the distro file of the same name (/usr/lib/modprobe.d/rpi-brcmfmac.conf,
# shipped by raspi-firmware since the Bookworm cycle) which sets roamoff=1.
# We need roaming *on* for the Pi to work properly with some access points,
# so we override it here.
options brcmfmac roamoff=0 feature_disable=0x282000
