#!/bin/bash
set -e

if [ "$1" = "purge" ]; then
    for unit in mod-midi-merger.service mod-midi-merger-broadcaster.service; do
        systemctl unmask "$unit" 2>/dev/null || true
    done
fi

#DEBHELPER#