#!/bin/bash -e

mkdir -p "${ROOTFS_DIR}/boot/firmware"

if ! [ -L "${ROOTFS_DIR}/boot/overlays" ]; then
	ln -s firmware/overlays "${ROOTFS_DIR}/boot/overlays"
fi

install -m 644 files/cmdline.txt "${ROOTFS_DIR}/boot/firmware/"

# No config.txt here on purpose. stage2/05-pistomp/03-run.sh installs the real
# one, overwriting whatever this stage left, so a second copy is only a place
# to edit a setting that never ships (f750ac5 set usb_max_current_enable in
# both, and the stage1 half did nothing). Nothing reads config.txt between
# here and there: no stage script, no package maintainer script on the image,
# and no kernel or initramfs hook.

for file in cmdline.txt config.txt; do
	printf "DO NOT EDIT THIS FILE\n\nThe file you are looking for has moved to %s\n" "/boot/firmware/${file}" > "${ROOTFS_DIR}/boot/${file}"
done
