#!/usr/bin/env python3
"""Collect a GDPR-oriented pi-Stomp support bundle and write a .tar.gz.

Intended for cockpit-pistomp-support: gather diagnostics useful for support,
strip personal identifiers, and leave a tarball the user can download and
send manually. Never includes WiFi credentials, SSH host keys, or NM
connection profiles.
"""
from __future__ import annotations

import argparse
import base64
import datetime as dt
import os
import re
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

REDACT_IP4 = re.compile(
    r"\b(?:(?:25[0-5]|2[0-4]\d|[01]?\d?\d)\.){3}"
    r"(?:25[0-5]|2[0-4]\d|[01]?\d?\d)\b"
)
REDACT_IP6 = re.compile(
    r"\b(?:[0-9a-fA-F]{1,4}:){2,7}[0-9a-fA-F]{1,4}\b|"
    r"\b(?:[0-9a-fA-F]{1,4}:){1,7}:\b|"
    r"\b::(?:[0-9a-fA-F]{1,4}:){0,6}[0-9a-fA-F]{1,4}\b"
)
REDACT_MAC = re.compile(r"\b(?:[0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}\b")
REDACT_EMAIL = re.compile(
    r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b"
)
REDACT_HOME = re.compile(r"/home/[A-Za-z0-9._-]+")
REDACT_SERIAL = re.compile(
    r"(?i)\b(serial(?:\s*(?:number|no\.?|#))?|iSerial|ID_SERIAL(?:_SHORT)?)"
    r"\s*[:=]\s*\S+"
)
REDACT_SSID = re.compile(
    r'(?i)\b(ssid|bssid)\s*[:=]\s*["\']?[^"\'\s]+["\']?'
)
REDACT_SECRET = re.compile(
    r"(?i)\b(password|passwd|psk|passphrase|secret|token|api[_-]?key)"
    r"\s*[:=]\s*\S+"
)
REDACT_AUTH_KEY = re.compile(
    r"\b(?:ssh-(?:rsa|ed25519|dss)|ecdsa-sha2-\S+)\s+\S+"
)

SERVICES = (
    "jack.service",
    "mod-host.service",
    "mod-ui.service",
    "mod-ala-pi-stomp.service",
    "firstboot.service",
    "NetworkManager.service",
    "avahi-daemon.service",
    "cockpit.socket",
    "pistomp-audio-irq.service",
    "wifi-check.service",
    "wifi-hotspot.service",
)


def redact(text: str) -> str:
    text = REDACT_SECRET.sub(r"\1=[REDACTED]", text)
    text = REDACT_SSID.sub(r"\1=[REDACTED_SSID]", text)
    text = REDACT_SERIAL.sub(r"\1=[REDACTED_SERIAL]", text)
    text = REDACT_AUTH_KEY.sub("[REDACTED_SSH_KEY]", text)
    text = REDACT_EMAIL.sub("[REDACTED_EMAIL]", text)
    text = REDACT_MAC.sub("[REDACTED_MAC]", text)
    text = REDACT_IP6.sub("[REDACTED_IP6]", text)
    text = REDACT_IP4.sub("[REDACTED_IP]", text)
    text = REDACT_HOME.sub("/home/[USER]", text)
    return text


def run(cmd: list[str], timeout: int = 60) -> str:
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except FileNotFoundError:
        return f"[command not found: {cmd[0]}]\n"
    except subprocess.TimeoutExpired:
        return f"[timeout after {timeout}s: {' '.join(cmd)}]\n"
    out = (proc.stdout or "") + (proc.stderr or "")
    if proc.returncode != 0 and not out.strip():
        out = f"[exit {proc.returncode}: {' '.join(cmd)}]\n"
    return out


def write_text(path: Path, content: str, *, do_redact: bool = True) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = redact(content) if do_redact else content
    path.write_text(data, encoding="utf-8", errors="replace")


def read_file(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        return f"[unreadable {path}: {exc}]\n"


def collect_into(workdir: Path, note: str) -> None:
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    write_text(
        workdir / "README.txt",
        (
            "pi-Stomp support bundle\n"
            f"Created (UTC): {stamp}\n"
            "\n"
            "This archive was generated by cockpit-pistomp-support.\n"
            "Personal identifiers (IP addresses, MAC addresses, emails,\n"
            "home-directory usernames, WiFi SSIDs, USB serials, passwords,\n"
            "and SSH public keys) are redacted before packaging.\n"
            "\n"
            "WiFi credentials, NetworkManager connection profiles, SSH host\n"
            "keys, and /boot/pistomp.conf are never included.\n"
            "\n"
            "Send this file only to the support channel you trust.\n"
        ),
        do_redact=False,
    )

    if note.strip():
        # User-authored for support; not auto-redacted.
        write_text(workdir / "user-note.txt", note.strip() + "\n", do_redact=False)

    write_text(workdir / "system" / "uname.txt", run(["uname", "-a"]))
    model_path = Path("/proc/device-tree/model")
    write_text(
        workdir / "system" / "model.txt",
        read_file(model_path) if model_path.exists() else "[no model]\n",
    )
    write_text(workdir / "system" / "uptime.txt", run(["uptime"]))
    write_text(workdir / "system" / "cmdline.txt", read_file(Path("/proc/cmdline")))
    write_text(workdir / "system" / "free.txt", run(["free", "-h"]))
    write_text(workdir / "system" / "df.txt", run(["df", "-h"]))
    write_text(
        workdir / "system" / "lsblk.txt",
        run(["lsblk", "-o", "NAME,SIZE,TYPE,FSTYPE,MOUNTPOINTS"]),
    )

    write_text(workdir / "network" / "ip-brief.txt", run(["ip", "-br", "addr"]))
    write_text(workdir / "network" / "ip-link.txt", run(["ip", "-br", "link"]))
    write_text(
        workdir / "network" / "nmcli-device.txt",
        run(
            [
                "nmcli",
                "-t",
                "-f",
                "DEVICE,TYPE,STATE,CONNECTION",
                "device",
                "status",
            ]
        ),
    )

    write_text(workdir / "usb" / "lsusb.txt", run(["lsusb"]))
    write_text(workdir / "audio" / "aplay-l.txt", run(["aplay", "-l"]))
    write_text(workdir / "audio" / "jack_lsp.txt", run(["jack_lsp", "-c"]))
    jack_default = Path("/etc/default/jack")
    write_text(
        workdir / "audio" / "jack-default.txt",
        read_file(jack_default)
        if jack_default.exists()
        else "[missing /etc/default/jack]\n",
    )

    dpkg = run(["dpkg-query", "-W", "-f=${Package}\\t${Version}\\n"])
    interesting = []
    for line in dpkg.splitlines():
        name = line.split("\t", 1)[0].lower()
        if any(
            k in name
            for k in (
                "pistomp",
                "jack",
                "mod-",
                "cockpit",
                "linux-image",
                "network-manager",
                "avahi",
                "rtirq",
                "alsa",
            )
        ):
            interesting.append(line)
    write_text(
        workdir / "packages" / "relevant.txt",
        ("\n".join(interesting) + "\n") if interesting else "",
    )

    for svc in SERVICES:
        write_text(
            workdir / "services" / f"{svc}.status.txt",
            run(["systemctl", "status", "--no-pager", "-l", svc]),
        )

    write_text(
        workdir / "journal" / "current-boot.txt",
        run(
            ["journalctl", "-b", "--no-pager", "-o", "short-iso", "-n", "8000"],
            timeout=120,
        ),
    )
    write_text(
        workdir / "journal" / "previous-boot.txt",
        run(
            [
                "journalctl",
                "-b",
                "-1",
                "--no-pager",
                "-o",
                "short-iso",
                "-n",
                "4000",
            ],
            timeout=120,
        ),
    )
    for unit in (
        "jack.service",
        "mod-host.service",
        "mod-ui.service",
        "mod-ala-pi-stomp.service",
        "firstboot.service",
    ):
        write_text(
            workdir / "journal" / f"{unit}.txt",
            run(
                [
                    "journalctl",
                    "-u",
                    unit,
                    "--no-pager",
                    "-o",
                    "short-iso",
                    "-n",
                    "2000",
                ],
                timeout=90,
            ),
        )

    for cfg in (Path("/boot/firmware/config.txt"), Path("/boot/config.txt")):
        if cfg.exists():
            write_text(workdir / "boot" / cfg.name, read_file(cfg))
            break

    boot_log = Path("/boot/firmware/boot.log")
    if boot_log.exists():
        data = read_file(boot_log)
        if len(data) > 512_000:
            data = data[-512_000:]
        write_text(workdir / "boot" / "boot.log.tail.txt", data)

    write_text(
        workdir / "REDACTION.txt",
        (
            "Redaction applied to collected text:\n"
            "  - IPv4 / IPv6 addresses → [REDACTED_IP] / [REDACTED_IP6]\n"
            "  - MAC / Bluetooth addresses → [REDACTED_MAC]\n"
            "  - Email addresses → [REDACTED_EMAIL]\n"
            "  - /home/<name> paths → /home/[USER]\n"
            "  - WiFi SSID/BSSID fields → [REDACTED_SSID]\n"
            "  - USB/serial tokens → [REDACTED_SERIAL]\n"
            "  - password/psk/secret/token fields → [REDACTED]\n"
            "  - SSH public key material → [REDACTED_SSH_KEY]\n"
            "\n"
            "Never included:\n"
            "  - /boot/pistomp.conf and WiFi credentials\n"
            "  - NetworkManager system-connections\n"
            "  - SSH host keys and authorized_keys\n"
            "  - /etc/shadow\n"
        ),
        do_redact=False,
    )


def make_tarball(srcdir: Path, outfile: Path) -> None:
    outfile.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(outfile, "w:gz") as tar:
        tar.add(srcdir, arcname=srcdir.name)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        help="Output .tar.gz path (default: under /tmp)",
    )
    parser.add_argument(
        "--note-file",
        help="Optional path to a user note to include as user-note.txt",
    )
    parser.add_argument(
        "--note-b64",
        help="Optional user note, base64-encoded (avoids stdin; Cockpit leaves stdin open)",
    )
    args = parser.parse_args()

    note = ""
    if args.note_b64:
        note = base64.b64decode(args.note_b64).decode("utf-8", errors="replace")
    elif args.note_file:
        note = Path(args.note_file).read_text(encoding="utf-8", errors="replace")

    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out = (
        Path(args.output)
        if args.output
        else Path(f"/tmp/pistomp-support-{stamp}.tar.gz")
    )

    with tempfile.TemporaryDirectory(prefix="pistomp-support-") as tmp:
        bundle = Path(tmp) / f"pistomp-support-{stamp}"
        bundle.mkdir()
        print(f"Collecting support data into {bundle.name}...", file=sys.stderr)
        collect_into(bundle, note)
        print(f"Writing {out}...", file=sys.stderr)
        make_tarball(bundle, out)
        # Readable by the cockpit session user for download.
        os.chmod(out, 0o644)

    print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
