name: build-rpi-preseed

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/rpi-preseed/**'
  pull_request:
    paths:
      - 'debpkgs/rpi-preseed/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: rpi-preseed
    secrets: inherit
