name: build-ffmpeg-pistomp

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/ffmpeg-pistomp/**'
      - 'config.sh'
  pull_request:
    paths:
      - 'debpkgs/ffmpeg-pistomp/**'
      - 'config.sh'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: ffmpeg-pistomp
    secrets: inherit
