name: build-pistomp-usb-automount

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/pistomp-usb-automount/**'
  pull_request:
    paths:
      - 'debpkgs/pistomp-usb-automount/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: pistomp-usb-automount
    secrets: inherit
