name: build-jack-capture

on:
  push:
    branches: [main]
    paths:
      - 'debpkgs/jack-capture/**'
      - 'config.sh'
  pull_request:
    paths:
      - 'debpkgs/jack-capture/**'
      - 'config.sh'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-deb.yml
    with:
      pkg: jack-capture
    secrets: inherit
